gobject-introspection 1.54.1-3
> $ /usr/bin/g-ir-scanner
> [...]
>     from giscanner._giscanner import collect_attributes
> ImportError: dynamic module does not define module export function (PyInit__giscanner)

g-ir-scanner uses 'python' in it's shebang, but _giscanner.dll is built
for python2.

Fix this by explicitly configuring to use python2, but really we need to
update this for python3.